version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "5050:5050"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env